{% set name = "tenacity" %}
{% set version = "9.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1169d376c297e7de388d18b4481760d478b0e99a777cad3a9c86e556f4b697cb

build:
  number: 1
  skip: true  # [py<37]
  script: {{ PYTHON }} -m pip install -vv --no-deps --no-build-isolation .

requirements:
  host:
    - pip
    - toml
    - wheel
    - python
    - setuptools >=21.0.0,!=24.0.0,!=34.0.0,!=34.0.1,!=34.0.2,!=34.0.3,!=34.1.0,!=34.1.1,!=34.2.0,!=34.3.0,!=34.3.1,!=34.3.2,!=36.2.0
    - setuptools_scm >=3.4
  run:
    - python

test:
  source_files:
    - tests
  imports:
    - tenacity
  requires:
    - pip
    - pytest
    - tornado
    - typeguard
  commands:
    - pip check
    - pytest tests

about:
  home: https://github.com/jd/tenacity
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache
  summary: Retry a flaky function whenever an exception occurs until it works
  description: |
    Tenacity is general-purpose retrying library, written in Python, to simplify the task of
    adding retry behavior to just about anything. It originates from a fork of Retrying
  doc_url: https://tenacity.readthedocs.io
  dev_url: https://github.com/jd/tenacity

extra:
  recipe-maintainers:
    - sodre
    - xylar
