{% set name = "tenacity" %}
{% set version = "8.0.0" %}
{% set sha256 = "6011fc69be55e0e20a9ceccdd8a7d969e42f892a81ea3a007de56e764d3551dd" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: "{{ PYTHON }} -m pip install -vv ."

requirements:
  host:
    - python >=3.6
    - pip
    - wheel
    - setuptools >=21.0.0,!=24.0.0,!=34.0.0,!=34.0.1,!=34.0.2,!=34.0.3,!=34.1.0,!=34.1.1,!=34.2.0,!=34.3.0,!=34.3.1,!=34.3.2,!=36.2.0
    - setuptools_scm >=3.4
    - toml
  run:
    - python >=3.6

test:
  imports:
    - tenacity
  requires:
    - pip
  commands:
    - pip check

about:
  home: http://github.com/jd/tenacity
  license: Apache 2.0
  license_file: LICENSE
  license_family: Apache
  summary: 'Retry a flaky function whenever an exception occurs until it works'

  description: |
    Tenacity is general-purpose retrying library, written in Python, to simplify the task of
    adding retry behavior to just about anything. It originates from a fork of Retrying
  doc_url: http://tenacity.readthedocs.io
  dev_url: http://github.com/jd/tenacity

extra:
  recipe-maintainers:
    - sodre
    - xylar
