{% set name = "tenacity" %}
{% set version = "8.2.3" %}
{% set sha256 = "5398ef0d78e63f40007c1fb4c0bff96e1911394d2fa8d194f77619c05ff6cc8a" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  skip: True  # [py>=38]
  script: {{ PYTHON }} -m pip install -vv --no-deps --no-build-isolation .

requirements:
  host:
    - pip
    - toml
    - wheel
    - python
    - setuptools 69.5.1
    - setuptools_scm 8.1.0
  run:
    - python

test:
  imports:
    - tenacity
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/jd/tenacity
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache
  summary: 'Retry a flaky function whenever an exception occurs until it works'
  description: |
    Tenacity is general-purpose retrying library, written in Python, to simplify the task of
    adding retry behavior to just about anything. It originates from a fork of Retrying
  doc_url: https://tenacity.readthedocs.io
  dev_url: https://github.com/jd/tenacity

extra:
  recipe-maintainers:
    - sodre
    - xylar
