{% set name = "tenacity" %}
{% set version = "5.0.4" %}
{% set sha256 = "a0c3c5f7ae0c33f5556c775ca059c12d6fd8ab7121613a713e8b7d649908571b" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
    - python
    - pbr
    - pip
  run:
    - python
    - futures >=3  # [py27]
    - monotonic >=0.6  # [py27]
    - six >=1.9.0

test:
  imports:
    - tenacity

about:
  home: http://github.com/jd/tenacity
  license: Apache 2.0
  license_file: LICENSE
  summary: 'Retry a flaky function whenever an exception occurs until it works'

  description: |
    Tenacity is general-purpose retrying library, written in Python, to simplify the task of 
    adding retry behavior to just about anything. It originates from a fork of Retrying
  doc_url: http://tenacity.readthedocs.io
  dev_url: http://github.com/jd/tenacity

extra:
  recipe-maintainers:
    - sodre
