travis:
  secure:
    BINSTAR_TOKEN: U1Pp1cvlmt4tSJCIbcc7KsAMpotgY+rZWvXe2QY97z+WlpLRR6l6/qyavE4ELo8Rck0U+BYIibGTIXqsYDVzfDNbNs1V1P5wD8ewpGmQTg91WvbdfRAQ9MfImAVgg6ORx2EQVCudLAr4+GiqoqeNHGnmtsiUTqMQZSUZWO5EhEfKNLVyln0u271aASa/80ond7WhxMVDcoLSF0XvfXVM+YHVmPOQST+/fpPWbY/U6IRzblFOC5YFccz/s/JjvESCMRvemJ2Wecif33sW8EO122/wvUZIBczzwNFam0SNoh+qzupIy1jLC5UBxL4DUshjz+aq1Rb+kL0cVAKWcBvd6caWvMbp5yWiFGnrdvf+vz07O0iCbn8Wgr7H0UqDyNJFuymkE44R2y1L+XalMPhrUjizG/kRXcEN3rJA4DiDevjg+UBkx1Xw/pTyZTKzFH8duEoIDTuyLCYrO0uESaTT3dhOEpAx6t3VR7v7u4tjsMucVc73fE9iTTsT9WkdhNcP0TbFX28QEoRfC0xBlPX3ZIlhmksnN/zMHPcvpO9pH36xjLmvc6pJOExOehpNy8tqXO+H65lHeqA8g09z0ehQBDJG3OyI1Q4+CpRZ92YZ4LxGeVxRYSjk3/q5sdF2PYHIQ5pACcD08p71IV4RQry4T1tQEh5qX0N9cY6BL+E+K9c=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
